### ISSUE TITLE
Missing exposure test of AnyCubic Photon OG with FHD Mono screen upgrade

### ISSUE THREAD

**Issue by jamesburton** [Photonsters/Resin-exposure-finder-v2#15]
Standard 5.5" Photon size, 1080x1920 resolution.
https://chitusystems.com/product/fhd-5-5-mono-lcd-for-elegoo-mars-elegoo-mars-pro/

NB: With the standard UC from the Photon OG it may need a slightly higher exposure range than most mono printers.

**Comment by X3msnake** [comment]
For the multiexposure test use UVTools instead ;)
