### ISSUE TITLE
Mars 2 Pro incompatibility

### ISSUE THREAD

**Issue by lienbacher** [Photonsters/Resin-exposure-finder-v2#7]
I've just tried running the calibration on a mars 2 pro mono and when running the printer says: "The resolution does not match (1440p)". I've been trying to run `BETA-xp2_CTB_1440x2560__050um_0.5-5s.zip`

**Comment by notrealdan** [comment]
Use the 1620x2560 file to match the screen resolution of a Mars 2 Pro.

**Comment by lienbacher** [comment]
omg, I really should have noticed this. thank you!
